package data;

import w.CacheableDoomObject;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * SubSector, as generated by BSP.
 */

public class mapsubsector_t implements CacheableDoomObject
{

    public char numsegs;
    /**
     * Index of first one, segs are stored sequentially.
     */
    public char firstseg;
    public mapsubsector_t()
    {

    }

    public static int sizeOf()
    {
        return 4;
    }

    @Override
    public void unpack(ByteBuffer buf)
            throws IOException
    {
        buf.order(ByteOrder.LITTLE_ENDIAN);
        numsegs = buf.getChar();
        firstseg = buf.getChar();

    }
}
